name: dart_orm
version: 0.0.9
description: >
  Easy-to-use and easy-to-setup database ORM for dart.
author: Ustimenko Sergey <ustims@gmail.com>
homepage: https://github.com/ustims/DartORM
dependencies:

dev_dependencies:
  unittest: '>=0.10.0'
  args: any
  coverage: any
  dart_orm_adapter_postgresql: any
  dart_orm_adapter_mongodb: any
  dart_orm_adapter_mysql: any